//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace CarWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int Id { get; set; }

        [Required]
        [Range(1900, Int32.MaxValue, ErrorMessage = "The field {0} must be greater than {1}.")]
        public int Year { get; set; }

        public string Colour { get; set; }

        [Required]
        [Display(Name = "Manufacturer")]
        public int ManufacturerID { get; set; }

        [Required]
        [Display(Name = "Model")]
        public int ModelID { get; set; }

        [Required]
        [Range(0, 1000000, ErrorMessage = "Mileage must be between {1} and {2}.")]
        public int Mileage { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }

        public virtual Model Model { get; set; }

    }
}
