//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace CarWorld
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Model()
        {
            this.Cars = new HashSet<Car>();
        }
    
        public int Id { get; set; }

        [Required]
        [Display(Name = "Model")]
        public string Name { get; set; }

        [Required]
        [Display(Name = "Manufacturer")]
        public int ManufacturerID { get; set; }

        [Range(2,10, ErrorMessage = "Number of Doors must be between {1} and {2}.")]
        public Nullable<int> Doors { get; set; }

        public string Details { get; set; }

        [Range(0.1, 50, ErrorMessage = "Engine Size must be between {1} and {2}.")]
        [Display(Name = "Engine Size")]
        public decimal EngineSize { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Car> Cars { get; set; }
    }
}
